fieldLayouts:
  1718244d-8e7d-40a9-bc84-db4afa59a095:
    tabs:
      -
        elementCondition: null
        elements:
          -
            autocapitalize: true
            autocomplete: false
            autocorrect: true
            class: null
            disabled: false
            elementCondition: null
            id: null
            instructions: null
            label: null
            max: null
            min: null
            name: null
            orientation: null
            placeholder: null
            readonly: false
            requirable: false
            size: null
            step: null
            tip: null
            title: null
            type: craft\fieldlayoutelements\assets\AssetTitleField
            uid: 65d9bd0b-1263-4f52-b93c-35c5c798128e
            userCondition: null
            warning: null
            width: 100
        name: Content
        uid: c59adafe-b00c-41d7-a20b-3722c4f409ba
        userCondition: null
fs: uploads
handle: siteAssets
name: 'site assets'
sortOrder: 1
titleTranslationKeyFormat: null
titleTranslationMethod: site
transformFs: ''
transformSubpath: ''
